### ISSUE TITLE
'opencv2/opencv.hpp' file not found

### ISSUE THREAD

**Issue by break200** [ura14h/OpenCVSample#1]
According to your requirements
In xcode version 10.2
I had to replace the framework however
It asks you that you can not find the file location as above.

**Comment by ura14h** [comment]
It is iOS target? macOS target? or both?

Each `opencv2.framework` have to be located to same position of `OpenCVSample_*.xcodeproj`.

**Comment by break200** [comment]
I am building a project with iOS target

**Comment by break200** [comment]
Thanks to the problem has been fixed.

**Comment by ura14h** [comment]
That's sound good. I'll close this issue.
